set nocompatible
filetype off 

set guicursor=
set termguicolors
set noshowmatch
set relativenumber
set nohlsearch
set hidden
set noerrorbells
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set relativenumber
set wrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set scrolloff=8
set noshowmode
set encoding=utf-8
set ruler
set updatetime=50
set colorcolumn=80
set laststatus=2
set clipboard=unnamedplus
